### ISSUE TITLE
Support for redmine 1.4.X?

### ISSUE THREAD

**Issue by m-ghaoui** [256MbTeam/Redmine-Scrumbler#63]
Hi,

Are there any plans on the horizon to support redmine version 1.4.X?

Thanks!

Y

**Comment by igorhmm** [comment]
It's a good question.

I did a try and is almost fine, just the configure section isn't working.

Thanks in advance

**Comment by m-ghaoui** [comment]
I installed scrumbler on the Bitnami Redmine stack version 1.4.0. When you go to the backlog link then the following error occurs:

Processing ScrumblerBacklogsController#show (for xxx.xxx.xxx.xxx at 2012-04-24 19:51:36) [GET]
  Parameters: {"project_id"=>"test", "controller"=>"scrumbler_backlogs", "action"=>"show"}
Rendering template within layouts/base
Rendering scrumbler_backlogs/show

```
ActionView::TemplateError (undefined method `without_version' for #<Array:0x883ce18>) on line #12 of vendor/plugins/redmine_scrumbler/app/views/scrumbler_backlogs/show.html.erb:
9: <%end%>
10: 
11: <!-- Draw backlog Page -->
12: <%= backlog_issues %>

    E:1:in `__send__'
    E:1:in `with_scope'
    vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:67:in `prepare_backlog_for_json'
    vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:77:in `prepare_backlogs_data_to_json'
    vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:84:in `backlog_issues'
    vendor/plugins/redmine_scrumbler/app/views/scrumbler_backlogs/show.html.erb:12
    config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering E:/BitNami_Redmine_Stack/apps/redmine/public/500.html (500 Internal Server Error)
```

I'm not a RoR developer but doing a quick scan of the code I see that the extension method "without_version" is used which does not exist in redmine version 1.4.0. I did a dirty hack and added some lines to the issues.rb file in redmine but that didn't really get me anywhere. 

Also clicking on the "settings" generated this error:

```

Processing ScrumblerSettingsController#show (for xxx.xxx.xxx.xxx at 2012-04-24 19:52:48) [GET]
  Parameters: {"controller"=>"scrumbler_settings", "project_id"=>"test", "action"=>"show"}
Rendering template within layouts/base
Rendering scrumbler_settings/show

ActionView::TemplateError (No route matches {:project_id=>#<Project id: 2, name: "Test", description: "This project is for testing purposes.", homepage: "", is_public: true, parent_id: nil, created_on: "2012-04-22 14:18:54", updated_on: "2012-04-24 15:00:20", identifier: "test", status: 1, lft: 7, rgt: 8>, :action=>"settings", :controller=>"scrumbler_sprints", :id=>1}) on line #19 of vendor/plugins/redmine_scrumbler/app/views/scrumbler_settings/_sprints.erb:
16:             </td>
17:             <td><%= l("scrumbler_sprint_#{sprint.status}") %></td>
18:             <% if authorize_for(:scrumbler_sprints, :settings)%> 
19:                 <td><%= link_to l(:button_edit), {:controller => :scrumbler_sprints, :action => :settings, :project_id => @project, :id => sprint.id}, :class=> "icon icon-scrumbler-settings" %></td>
20:             <%end%>
21:         </tr>
22:         <% end %>

    vendor/plugins/redmine_scrumbler/app/views/scrumbler_settings/_sprints.erb:19
    vendor/plugins/redmine_scrumbler/app/views/scrumbler_settings/_sprints.erb:12
    app/views/common/_tabs.html.erb:24
    app/views/common/_tabs.html.erb:23:in `each'
    app/views/common/_tabs.html.erb:23
    app/helpers/application_helper.rb:231:in `render_tabs'
    vendor/plugins/redmine_scrumbler/app/views/scrumbler_settings/show.html.erb:9
    config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering E:/BitNami_Redmine_Stack/apps/redmine/public/500.html (500 Internal Server Error)
```

So I think that scrumbler needs to be modified to support redmine 1.4.X

**Comment by slanglade** [comment]
Exactly the same issues here !

**Comment by xeta** [comment]
fixed in c5b0667fedd7e130dec5760c0a9f0e9c5ca7255e

**Comment by xeta** [comment]
Get the last version from 'master' and try again. It is worked for me under Redmine 1.4.1 and Ruby 1.9.3

**Comment by m-ghaoui** [comment]
Cool! I'll download it soon and test it.

**Comment by slanglade** [comment]
Many thanks ! That's cool, indeed.

**Comment by ghost** [comment]
Hi, sorry i now this issue is closed, but i stil get this template error by clicking on the "settings". My log:

Processing ScrumblerSettingsController#show (for xxx.xxx.xxx.xxx at 2012-04-30 16:37:38) [GET]
  Parameters: {"project_id"=>"sigem001", "controller"=>"scrumbler_settings", "action"=>"show"}
Rendering template within layouts/base
Rendering scrumbler_settings/show

ActionView::TemplateError (No route matches {:project_id=>#<Project id: 2, name: "SIGEM", description: "Un sistema de gestiÃ³n empresarial integrado con lo...", homepage: "", is_public: true, parent_id: nil, created_on: "2012-04-29 17:55:06", updated_on: "2012-04-29 17:55:06", identifier: "sigem001", status: 1, lft: 3, rgt: 8>, :action=>"settings", :id=>1, :controller=>"scrumbler_sprints"}) on line #19 of vendor/plugins/redmine_scrumbler/app/views/scrumbler_settings/_sprints.erb:
16:                     </td>
17:                     <td><%= l("scrumbler_sprint_#{sprint.status}") %></td>
18:                     <% if authorize_for(:scrumbler_sprints, :settings)%>
19:                             <td><%= link_to l(:button_edit), {:controller => :scrumbler_sprints, :action => :settings, :project_id => @project, :id => sprint.id}, :class=> "icon icon-scrumbler-settings" %></td>
20:                     <%end%>
21:             </tr>
22:             <% end %>

Redmine: 1.4.1 (bitnami stack)
Scrumbler plugin: 1.5

**Comment by xeta** [comment]
Thanks for testing!
I think, that it fix it in 1d8002f2bbb7168c166000ba364045c2de4851ee
Try last version from master branch.

**Comment by ghost** [comment]
Thanks xeta, it works perfect! I just check out the master branch. Great plugin!

**Comment by cforce** [comment]
The actula trunk stopped working with redmine 1.4.

Error message:
    undefined method `application' for Rails:Module

Can u please branch for 1.4 compatibilty. Some won't upgrade so soon.

**Comment by jashen** [comment]
I am in the same boat as cforce.
