### ISSUE TITLE
500 error while adding project Version

### ISSUE THREAD

**Issue by adroid** [256MbTeam/Redmine-Scrumbler#17]
Hi

I just cloned latest Redmine-Scrumbler and when adding version to project, I get 500 error.
Redmine version 1.3.1.

Log output:

NoMethodError (undefined method `settings' for #<ScrumblerSprint:0x7fda41f49a70>):
  vendor/plugins/redmine_scrumbler/app/models/scrumbler_sprint.rb:89:in`after_initialize'
  app/controllers/versions_controller.rb:89:in `create'
  /usr/lib64/ruby/1.8/webrick/httpserver.rb:104:in`service'
  /usr/lib64/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/lib64/ruby/1.8/webrick/server.rb:173:in`start_thread'
  /usr/lib64/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/lib64/ruby/1.8/webrick/server.rb:162:in`start_thread'
  /usr/lib64/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/lib64/ruby/1.8/webrick/server.rb:92:in`each'
  /usr/lib64/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/lib64/ruby/1.8/webrick/server.rb:23:in`start'
  /usr/lib64/ruby/1.8/webrick/server.rb:82:in `start'

**Comment by zloydadka** [comment]
did you run migrations?

**Comment by adroid** [comment]
Thanks for pointing in that direction. Finally I got it working with little hacking.

I migrated...but there were issues with it. After install and migrate, I removed Scrumbler plugin to debug issues which rised after upgrading Redmine to 1.3.1(wasn't sure which module did it).
Scrumbler removal included steps like:
   1) command: rake db:migrate:plugin NAME=redmine_scrumbler VERSION=0 RAILS_ENV=production
   2) folder removal

That 'down' migration command produced error: http://pastebin.com/c2VW7Fqk
Probably because table 'scrumbler_sprint_statuses' was already removed in 'up' migrate in '20111018172704_update_scrumbler_maintrackers.rb'

After removal I installed Scrumbler plugin again but it didn't work.(that version adding issue I posted first)

Now I was able to learn how Redmine works and I did these steps:
  1) deleted all Scrumbler related entries from 'schema_migrations' table
  2) deleted all tables leftovers from database. (tables with name scrumbler_*)
  3) migrated again
And now it seems to work. Sorry for that panic. :)
